# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Image.create([{:image => File.new('/home/nyros/Documents/geetha/2019/Foodfieimages/aamshrikand.jpg',"r"), :dish_id => 2},{:image => File.new('/home/nyros/Documents/geetha/2019/Foodfieimages/burittos.jpg',"r"), :dish_id => 3},{:image => File.new('/home/nyros/Documents/geetha/2019/Foodfieimages/chickenbiryani.jpg',"r"), :dish_id => 4},{:image => File.new('/home/nyros/Documents/geetha/2019/Foodfieimages/dumbiryani.jpg',"r"), :dish_id => 5},{:image => File.new('/home/nyros/Documents/geetha/2019/Foodfieimages/sandesh.jpg',"r"), :dish_id => 6},{:image => File.new('/home/nyros/Documents/geetha/2019/Foodfieimages/shahi tuka.jpg',"r"), :dish_id => 7},{:image => File.new('/home/nyros/Documents/geetha/2019/Foodfieimages/tofu.jpg',"r"), :dish_id => 8},{:image => File.new('/home/nyros/Documents/geetha/2019/Foodfieimages/payasam.jpg',"r"), :dish_id => 9},{:image => File.new('/home/nyros/Documents/geetha/2019/Foodfieimages/fishmolle.JPG',"r"), :dish_id => 10},{:image => File.new('/home/nyros/Documents/geetha/2019/Foodfieimages/pasta.jpg',"r"), :dish_id => 11}])
# Review.create([{review:'Amazing food at a big and spacious hotel primley located. We had been for lunch and were waiting eagerly so that we can feast on the variety of the delicacies served. Good option for vegetarian people who want to have',rating:4,dish_id:159,user_id:2},{review:'Amazing food at a big and spacious hotel primley located. We had been for lunch and were waiting eagerly so that we can feast on the variety of the delicacies served. Good option for vegetarian people who want to have',rating:3,dish_id:158,user_id:2},{review:'Amazing food at a big and spacious hotel primley located. We had been for lunch and were waiting eagerly so that we can feast on the variety of the delicacies served. Good option for vegetarian people who want to have',rating:5,dish_id:157,user_id:2},{review:'Amazing food at a big and spacious hotel primley located. We had been for lunch and were waiting eagerly so that we can feast on the variety of the delicacies served. Good option for vegetarian people who want to have',rating:4,dish_id:156,user_id:2},{review:'Amazing food at a big and spacious hotel primley located. We had been for lunch and were waiting eagerly so that we can feast on the variety of the delicacies served. Good option for vegetarian people who want to have',rating:4,dish_id:154,user_id:2},{review:'Amazing food at a big and spacious hotel primley located. We had been for lunch and were waiting eagerly so that we can feast on the variety of the delicacies served. Good option for vegetarian people who want to have',rating:5,dish_id:153,user_id:2},{review:'Amazing food at a big and spacious hotel primley located. We had been for lunch and were waiting eagerly so that we can feast on the variety of the delicacies served. Good option for vegetarian people who want to have',rating:3,dish_id:152,user_id:1},{review:'Amazing food at a big and spacious hotel primley located. We had been for lunch and were waiting eagerly so that we can feast on the variety of the delicacies served. Good option for vegetarian people who want to have',rating:4,dish_id:151,user_id:2},{review:'Amazing food at a big and spacious hotel primley located. We had been for lunch and were waiting eagerly so that we can feast on the variety of the delicacies served. Good option for vegetarian people who want to have',rating:2,dish_id:148,user_id:1},{review:'Amazing food at a big and spacious hotel primley located. We had been for lunch and were waiting eagerly so that we can feast on the variety of the delicacies served. Good option for vegetarian people who want to have',rating:5,dish_id:147,user_id:1},{review:'Amazing food at a big and spacious hotel primley located. We had been for lunch and were waiting eagerly so that we can feast on the variety of the delicacies served. Good option for vegetarian people who want to have',rating:3,dish_id:146,user_id:1}])

